# Generated by Django 5.1.2 on 2024-10-10 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClubMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('city', models.CharField(choices=[('bagerhat', 'Bagerhat'), ('bandarban', 'Bandarban'), ('barguna', 'Barguna'), ('barisal', 'Barisal'), ('bhola', 'Bhola'), ('bogura', 'Bogura'), ('brahmanbaria', 'Brahmanbaria'), ('chandpur', 'Chandpur'), ('chattogram', 'Chattogram'), ('chuadanga', 'Chuadanga'), ('comilla', 'Comilla'), ('coxsbazar', "Cox's Bazar"), ('dhaka', 'Dhaka'), ('dinajpur', 'Dinajpur'), ('faridpur', 'Faridpur'), ('feni', 'Feni'), ('gaibandha', 'Gaibandha'), ('gazipur', 'Gazipur'), ('gopalganj', 'Gopalganj'), ('habiganj', 'Habiganj'), ('jamalpur', 'Jamalpur'), ('jashore', 'Jashore'), ('jhenaidah', 'Jhenaidah'), ('joypurhat', 'Joypurhat'), ('khagrachari', 'Khagrachari'), ('khulna', 'Khulna'), ('kishoreganj', 'Kishoreganj'), ('kurigram', 'Kurigram'), ('kushtia', 'Kushtia'), ('lakshmipur', 'Lakshmipur'), ('lalmonirhat', 'Lalmonirhat'), ('madaripur', 'Madaripur'), ('magura', 'Magura'), ('manikganj', 'Manikganj'), ('meherpur', 'Meherpur'), ('moulvibazar', 'Moulvibazar'), ('munshiganj', 'Munshiganj'), ('mymensingh', 'Mymensingh'), ('naogaon', 'Naogaon'), ('narail', 'Narail'), ('narayanganj', 'Narayanganj'), ('narsingdi', 'Narsingdi'), ('natore', 'Natore'), ('netrokona', 'Netrokona'), ('nilphamari', 'Nilphamari'), ('noakhali', 'Noakhali'), ('pabna', 'Pabna'), ('panchagarh', 'Panchagarh'), ('patuakhali', 'Patuakhali'), ('pirojpur', 'Pirojpur'), ('rajbari', 'Rajbari'), ('rajshahi', 'Rajshahi'), ('rangamati', 'Rangamati'), ('rangpur', 'Rangpur'), ('satkhira', 'Satkhira'), ('shariatpur', 'Shariatpur'), ('sherpur', 'Sherpur'), ('sirajganj', 'Sirajganj'), ('sunamganj', 'Sunamganj'), ('sylhet', 'Sylhet'), ('tangail', 'Tangail'), ('thakurgaon', 'Thakurgaon')], max_length=20)),
            ],
        ),
    ]
