# Generated by Django 5.1.2 on 2024-10-15 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serverclub', '0004_remove_content_body_remove_content_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Content',
        ),
        migrations.AddField(
            model_name='post',
            name='like',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
