# Generated by Django 5.1.2 on 2024-10-19 10:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serverclub', '0006_post_content_type_alter_post_image_alter_post_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='content_type',
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.CharField(max_length=500, validators=[django.core.validators.MinLengthValidator(70)]),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
