# Generated by Django 5.1.2 on 2024-10-19 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serverclub', '0007_remove_post_content_type_alter_post_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
